### ISSUE TITLE
evaluate different source for github pages

### ISSUE THREAD

**Issue by Xiphe** [lassediercks/design#2]
Not sure how your publishing works exactly, but this might be interesting for you: [configuring-a-publishing-source-for-github-pages](https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/)

**Comment by lassediercks** [comment]
it's already creating the gh-page from master

**Comment by Xiphe** [comment]
ah, was confused by https://github.com/lassediercks/design/blob/59c0a927cb936ce04c4fcc2221cdcbc12092af7a/deployToGithubPages.sh

**Comment by lassediercks** [comment]
oh good hint, that's deprecated and I'll remove it now
